[project]
name = "optitrack"
version = "0.0.1"
requires-python = ">=3.7"
description = "Optitrack library"
dependencies = [
    'numpy>=1.2'
]
[build-system]
requires = ["setuptools>=6.10"]
build-backend = "setuptools.build_meta"
